### ISSUE TITLE
Multiple inputs from file

### ISSUE THREAD

**Issue by tofu1077** [tragdate/gptube-cli#1]
Please make a feature where I can have multiple links in a file and give the file to the command.
Output should be a file with the responses, labeled video1: response, video2: response etc..

**Comment by ZmoleCristian** [comment]
Added in the new rust version you can use gptube-cli -l 'listFile'
Note, it creates multiple Result files as before, you can just
```
cd yourWorkingFolder
gptube-cli -l 'listFile'
cat Result* > allResults 
```
if you want to make a singural file with all the results from the list
* when `-l` is provided the restul will have two newlines at the end for readability if you concatenate your files
